name: alagy
description: ''
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_cloud_firestore: ^5.4.4
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  connectivity_plus: ^6.1.3
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1
  badges: ^3.1.2
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0


  
  flutter_lints: ^5.0.0


flutter:
  generate: true
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg


