// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLduaIo49exBtG0o-mEdP1beFLY27_mDU',
    appId: '1:81987773272:android:360e3aa2f597c274d37b2d',
    messagingSenderId: '81987773272',
    projectId: 'alagy-92af4',
    storageBucket: 'alagy-92af4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhpW2Cilvj5QbU7p-kn5WU6sSv2wCczW4',
    appId: '1:81987773272:ios:c70a60190de19b02d37b2d',
    messagingSenderId: '81987773272',
    projectId: 'alagy-92af4',
    storageBucket: 'alagy-92af4.firebasestorage.app',
    androidClientId: '81987773272-1hj1eq7bm1iktbj2j0qo5gquanf7o8pc.apps.googleusercontent.com',
    iosClientId: '81987773272-i9q8r9hk9h0cvhgv7pok2q2rrivr0td4.apps.googleusercontent.com',
    iosBundleId: 'com.example.alagy',
  );

}