// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLduaIo49exBtG0o-mEdP1beFLY27_mDU',
    appId: '1:81987773272:android:9234280e4f26b7c9d37b2d',
    messagingSenderId: '81987773272',
    projectId: 'alagy-92af4',
    storageBucket: 'alagy-92af4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhpW2Cilvj5QbU7p-kn5WU6sSv2wCczW4',
    appId: '1:81987773272:ios:6309e7a1bfde10efd37b2d',
    messagingSenderId: '81987773272',
    projectId: 'alagy-92af4',
    storageBucket: 'alagy-92af4.firebasestorage.app',
    androidClientId: '81987773272-01qmn0av547u3dkild9sksk40tl1g765.apps.googleusercontent.com',
    iosClientId: '81987773272-2ipgj3ot2mkounvnekomedsr15kv6gpt.apps.googleusercontent.com',
    iosBundleId: 'com.alagy.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWf4aHrVQvsMP-IWxaylhXDOOT5PxWtms',
    appId: '1:81987773272:web:63a0e0842d4a752dd37b2d',
    messagingSenderId: '81987773272',
    projectId: 'alagy-92af4',
    authDomain: 'alagy-92af4.firebaseapp.com',
    storageBucket: 'alagy-92af4.firebasestorage.app',
    measurementId: 'G-3FYQXJBQ22',
  );

}