import 'package:alagy/core/common/enities/payment_type.dart';
import 'package:alagy/features/doctor_details/data/models/doctor_appointment.dart';
import 'package:alagy/features/doctor_details/data/repositories/doctor_repository.dart';
import 'package:alagy/features/payment/data/repositories/payment_repository.dart';
import 'package:alagy/features/settings/data/models/notification_model.dart';
import 'package:alagy/features/settings/data/repositories/notification_repository.dart';
import 'package:bloc/bloc.dart';
import 'package:injectable/injectable.dart';
import 'package:alagy/features/payment/data/models/payment_model.dart'; // Add
import 'package:intl/intl.dart';

part 'payment_state.dart';

@injectable
class PaymentCubit extends Cubit<PaymentState> {
  final PaymentRepository _paymentRepository;
  final DoctorRepository _doctorRepository;
  final NotificationRepository _notificationRepository;

  PaymentCubit(this._doctorRepository, this._notificationRepository,
      {required PaymentRepository paymentRepository})
      : _paymentRepository = paymentRepository,
        super(const PaymentState());

  void onSelectOption(PaymentType option) {
    if (state.selectedOption != option) {
      emit(state.copyWith(selectedOption: option));
    }
  }

  initAppointment(DoctorAppointment appointment) {
    emit(state.copyWith(appointment: appointment));
  }

  makeAppointment(DoctorAppointment appointment, String uid) async {
    emit(state.copyWith(status: PaymentStatus.loading));
    final response = await _doctorRepository.makeAppointment(appointment, uid);
    response.fold(
      (l) => emit(
          state.copyWith(status: PaymentStatus.error, errorMessage: l.message)),
      (r) => emit(state.copyWith(status: PaymentStatus.appointmentCreated)),
    );
  }

  /// Creates an appointment confirmation notification
  Future<void> createAppointmentNotification({
    required String userId,
    required String doctorName,
    required DateTime appointmentDate,
    required String appointmentTime,
  }) async {
    final formattedDate = DateFormat('MMM dd, yyyy').format(appointmentDate);

    await createNotification(
      userId: userId,
      title: 'Appointment Confirmed',
      body:
          'Your appointment with Dr. $doctorName is confirmed for $formattedDate at $appointmentTime',
      type: 'appointment_confirmation',
      data: {
        'doctorName': doctorName,
        'appointmentDate': appointmentDate.toIso8601String(),
        'appointmentTime': appointmentTime,
      },
    );
  }

  /// Creates a notification for a user
  Future<void> createNotification({
    required String userId,
    required String title,
    required String body,
    required String type,
    Map<String, dynamic>? data,
    String? imageUrl,
    String? actionUrl,
  }) async {
    try {
      final notification = NotificationModel(
        id: '', // Will be generated by Firestore
        title: title,
        body: body,
        type: type,
        data: data,
        isRead: false,
        createdAt: DateTime.now(),
        imageUrl: imageUrl,
        actionUrl: actionUrl,
      );

      final result = await _notificationRepository.createNotification(
        userId,
        notification,
      );

      result.fold(
        (failure) => print('Failed to create notification: ${failure.message}'),
        (notificationId) =>
            print('Notification created with ID: $notificationId'),
      );
    } catch (e) {
      print('Error creating notification: $e');
    }
  }

  Future<void> processPayment({
    required double amount,
    required String orderId,
    required String customerName,
    required String customerEmail,
    required String customerPhone,
    required String customerFirstName,
    required String customerLastName,
    required String city,
    required String country,
  }) async {
    if (state.selectedOption == null) return;
    emit(state.copyWith(status: PaymentStatus.loading));

    try {
      final payload = {
        'amount': amount * 100,
        'currency': 'EGP',
        'payment_methods': ['card'],
        'items': [
          {
            'name': 'Doctor Appointment',
            'amount': amount * 100,
            'description': 'Medical consultation',
            'quantity': 1
          }
        ],
        'billing_data': {
          'apartment': 'N/A',
          'first_name': customerFirstName,
          'last_name': customerLastName,
          'street': 'N/A',
          'building': 'N/A',
          'phone_number': customerPhone,
          'city': city,
          'country': country,
          'email': customerEmail,
          'floor': 'N/A',
          'state': 'N/A'
        },
        'special_reference': orderId,
        'notification_url':
            'https://webhook.site/f60597f3-97b9-4992-90e1-6f98a63fc32d',
        'redirection_url': 'https://www.google.com/'
      };

      final intentionResult = await _paymentRepository.createIntention(
        payload: payload,
      );

      final paymentKey = intentionResult['client_secret'] as String;
      emit(state.copyWith(
          status: PaymentStatus.success, paymentKey: paymentKey));
    } catch (e) {
      print(e.toString());
      emit(state.copyWith(
        status: PaymentStatus.error,
        errorMessage: 'Payment processing failed',
      ));
    }
  }

  Future<void> savePayment(PaymentModel payment) async {
    try {
      await _paymentRepository.savePayment(payment);
    } catch (e) {
      print('Error saving payment: $e');
    }
  }
}
