name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
      
      - run: pod repo update
        working-directory: ios

      - name: Build iOS Simulator Version
        run: flutter build ios --simulator

      - name: Prepare Appetize.io Upload
        run: |
          mkdir -p Payload
          cp -r build/ios/iphonesimulator/Runner.app Payload/
          tar -czvf FlutterApp.tar.gz Payload/Runner.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlutterApp
          path: FlutterApp.tar.gz
