name: iOS-ipa-build

on:
  workflow_dispatch:

permissions:
  contents: write  # Allows uploading releases

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
      
      - run: pod repo update
        working-directory: ios


      # ✅ Build for Simulator (outputs in `build/ios/iphonesimulator`)
      - run: flutter build ios --simulator --no-codesign



      # ✅ Prepare iOS Simulator App Archive
      - run: mkdir Payload
        working-directory: build/ios/iphonesimulator
      - run: mv Runner.app Payload
        working-directory: build/ios/iphonesimulator
      - run: zip -qq -r -9 FlutterSimulatorExport.zip Payload
        working-directory: build/ios/iphonesimulator



      # ✅ Upload iOS Simulator Build
      - name: Upload iOS Simulator Zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphonesimulator/FlutterSimulatorExport.zip
          tag: v1.0
          overwrite: true
