name: iOS-ipa-build

on:
  workflow_dispatch:

permissions:
  contents: write  # Ensure GITHUB_TOKEN has write access

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get Flutter Dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Setup Xcode CLI
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install CocoaPods Dependencies
        run: |
          sudo gem install cocoapods
          arch -x86_64 pod install --repo-update
        working-directory: ios

      - name: Verify Flutter Plugins
        run: flutter pub deps

      - name: Build iOS App (Release)
        run: flutter build ios --release --no-codesign

      - name: Prepare IPA Export
        run: |
          mkdir Payload
          mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Zip IPA File
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
